### ISSUE TITLE
Create filter for exporting objects with valid properties for OSM

### ISSUE THREAD

**Issue by gplv2** [gplv2/grbtool#11]
`let delarr = ["size_grb_building", "source:geometry:uidn", "source", "H_DTM_MIN", "H_DTM_GEM", "H_DSM_MAX", "H_DSM_P99", "HN_MAX", "HN_P99", "detection_method", "size_shared", "size_source_building","auto_building"]; `

auto_building needs to become building when it's present.

**Comment by timcouwelier** [comment]
When working with current version, there is a 'building' tag already assigned.
Does this mean that step is already in action, and you just want to deleted the others?

**Comment by timcouwelier** [comment]
In addition: do you want to remove them from the 'export' from staging to JOSM already? If so, we need to make note of it for the docs. Current play is using the filter in JOSM, which I suppose is fine while the beta runs.

In beta you probably actually WANT the reasoning to show?

**Comment by gplv2** [comment]
be3c2629460a504187c82b5b90f49b0f719a2aba

**Comment by gplv2** [comment]
It's just an internal ticket,  the data is as-is in the browser, only at time of export the tags are changed into the proper tags (like geometry:source:ref = entity/oidn ) that's why you see them still in the tool.  It's a lot easier to keep the functionality working like that , instead of changing all code behind it, just do it at export.  This works now btw,

**Comment by gplv2** [comment]
@timcouwelier see the commit referenced earlier.  the code is quite readable to see exactly what it does.
