### ISSUE TITLE
Add a 'never upload' tag to the GRB data

### ISSUE THREAD

**Issue by pietervdvn** [gplv2/grbtool#15]
The GRB data should be reviewed first, but it is all to easy to accidentally have the GRB data selected and upload that, thinking it is the reviewed and merged dataset.

This can easily be added according to the [file format wiki page](https://wiki.openstreetmap.org/wiki/JOSM_file_format)

`The osm element can have the upload attribute with the value false to discourage uploads or with the value never to completely disable accidental uploads.`

**Comment by gplv2** [comment]
fixed in commit:f40b18ccc2260fac88b0bb584701eac6f5b283de

**Comment by pietervdvn** [comment]
:tada: 

Lovely, that is gonna prevent a few quite disastrous accidental uploads

**Comment by gplv2** [comment]
Yes, it will ;-)
