### ISSUE TITLE
Use OSM.org tilelayer instead of OSM.be because it updates faster

### ISSUE THREAD

**Issue by pietervdvn** [gplv2/grbtool#16]
Although I love the Belgian baselayer, the OSM value has more added value, because it is easier to spot where the houses are still missing and where I should start importing again.

**Comment by joostschouppe** [comment]
Both are available; the Belgian tiles provide a nice "before" image

**Comment by gplv2** [comment]
Indeed, both layers are present, it just defaults to the belgian because it's more reliable, we had issues with OSM servers, never with our own afaik.

**Comment by pietervdvn** [comment]
Yep, I discovered the other layers a few days after opening the issue ;p
