### ISSUE TITLE
Automatically redirect to the https-version of the site - this fixes a bug with JOSM

### ISSUE THREAD

**Issue by pietervdvn** [gplv2/grbtool#17]
If I use the http-version, the site cannot connect with JOSM via remote control, but it works via the https-version of the site, regardless of the selected options.

**Comment by gplv2** [comment]
Not sure if this is what we want, the problem here is not everyone manages to setup JOSM with the SSL version.  Would like more feedback on this bug, can you point me to the JOSM bug information ?

**Comment by pietervdvn** [comment]
The problem is that the grb-tool tries to talk to JOSM via the same protocol as what the website was loaded with. So, if the GRB-tool is loaded via HTTP, it'll try to talk to JOSM via HTTP. If the website is loaded via HTTPS, it'll try to use HTTPS for remote control. This seems to be independent of the option that is selected in the UI.

**Comment by gplv2** [comment]
yes it's indeed an issue that can't be tackled entirely due to browsers defaults.  I know what you mean.  The site should however already default to https.   Are you not seeing this now ?

**Comment by gplv2** [comment]
This is obsolete now since JOSM changed to call non-secure version by default
