### ISSUE TITLE
Remove all google stuff

### ISSUE THREAD

**Issue by gplv2** [gplv2/grbtool#3]
remove the google search option instead of nominatim (nobody uses this )
remove google background layers , not really usefull

**Comment by gplv2** [comment]
This is on the backburner for the moment.   It's still interesting to see google sat pics.  But it would be nice to not have to depend on google too much. (hence openlayers)

**Comment by timcouwelier** [comment]
Why google over 'older AIV aerial imagery'? 
I'd see added value in 'dated' older imagery to track if a building may indeed have disappeared over time..

**Comment by gplv2** [comment]
it's not the maps in the first place, but the library to geocode addresses (search options).  it's not a priority this one, we can put it on hold, I rather build stuff than delete.

**Comment by gplv2** [comment]
All external JS code is now self-hosted except google maps.  Disabling google map api load in the browser should now be possible with limited functionality (address search will not work due to usage of google geocoder, and the google map backgrounds will also not be loaded).  All the rest should work fine now without javascript errors when you block the load of google map.
