### ISSUE TITLE
URL GET limit size workaround

### ISSUE THREAD

**Issue by gplv2** [gplv2/grbtool#7]
Browsers implement a limit on what a GET call can be, with the integration of JOSM, this is problematic as the GET call with many objects will cause problems, especially on windows platform it seems to be an issue (linux and MAC are not as affected as the limits seem harder).
It also depends on the type of browsers.

The following error will be see when hitting this limit.
![afbeelding](https://user-images.githubusercontent.com/907459/54613781-98f23400-4a5b-11e9-8c7f-579054c6ac70.png)

We should probably trap this error properly by measuring the length.   Find a workaround to support this size but at the same time limit what can be exported at once

**Comment by timcouwelier** [comment]
Is there an option to 'catch' this error and feed a proper response into 'Info' status box ?

**Comment by gplv2** [comment]
Probably not, the error comes from the browser itself (inside JS) and it throws an error, we can try to catch it with an exception maybe, but it's hard to reproduce this for me being on linux.  We could calculate the size of the payload however.   I think it's probably best to wrap this in a try/catch block

**Comment by gplv2** [comment]
catch problem added https://github.com/gplv2/grbtool/commit/719acbeecdc6eb9cd1ddd62cb452205935df7a77

**Comment by gplv2** [comment]
upload of XML export data back to server works : ae2d6529f6453d75b6737c5313bd25624ed5a879

**Comment by gplv2** [comment]
Download needs to be implemented  (although it's just an URL).  Need to be authenticated in order to be able to do this.

**Comment by gplv2** [comment]
Alternative load method has been built, a file will be created from the data and stored on the server by a backend API call, that file is stored in public storage where it can be downloaded manually or by clicking a button in the gui that will trigger JOSM to make a get file request to download a file.  This is working now.  But it is now a workaround on the size limit of the exported data.   Control mechanism still needed.

**Comment by gplv2** [comment]
Workaround for large exports seems to work
