### ISSUE TITLE
Not-maximized map window

### ISSUE THREAD

**Issue by timcouwelier** [gplv2/grbtool#8]
Map window doesn't show as large as it could, also implies I can't toggle all layer settings.
1920x1200 screen resolution on a win8.1 machine.

![afbeelding](https://user-images.githubusercontent.com/35382029/54615821-06539400-4a5f-11e9-9da0-49ab4317127c.png)

**Comment by gplv2** [comment]
Can you try to resize your window and see what happens , like doubleclick to maximize and then reverse. the map should follow the canvas size.

**Comment by timcouwelier** [comment]
Oh... 

If my window is maximized when I load the page, it loads nicely, whatever I resize to afterwards.
If browser is not maximized when I load the page initially, it acts strange as shown.. and remains to do so after resizing.

**Comment by gplv2** [comment]
It's a calculation I guess.  altough the map size should follow the containing diff. I calculate the map size to make sure the notificatios at the bottom are in view.

**Comment by gplv2** [comment]
I added a resize function ,  I still need to figure out why it doesn't stretch out, but the resize will take care of the format when you load non-maximised.  The site is however a bit made for maximizing (not fullscreen)

**Comment by gplv2** [comment]
https://github.com/gplv2/grbtool/commit/0d4de9affe337435d5d474f63d0a38160d0f1306

**Comment by gplv2** [comment]
this commit fixes this problem in chrome for me. f322fa1c01e2444b5dc5b9065e7b150380369285

**Comment by gplv2** [comment]
Please close issue when reviewed

**Comment by timcouwelier** [comment]
Tested - confirmed to be working and functional.
