### ISSUE TITLE
Documentation for Firefox users

### ISSUE THREAD

**Issue by timcouwelier** [gplv2/grbtool#9]
In JOSM, set up like this (including the certificate):
![afbeelding](https://user-images.githubusercontent.com/35382029/54622602-263c8500-4a6a-11e9-8769-854066c96448.png)

Try to load this page: https://127.0.0.1:8112/version

You may end up getting this:
![afbeelding](https://user-images.githubusercontent.com/35382029/54622686-4704da80-4a6a-11e9-8337-58b95174ceec.png)

Which you can solve in three clicks, doing this:
![afbeelding](https://user-images.githubusercontent.com/35382029/54622720-5552f680-4a6a-11e9-9baf-35550c6e41f1.png)

And once you've done that, the page should load, showing something like this:
![afbeelding](https://user-images.githubusercontent.com/35382029/54622756-6b60b700-4a6a-11e9-82d3-02f9b4b7405c.png)

**Comment by gplv2** [comment]
Think this is fixed now by the browsers excluding localhost from needing a valid certificate.
